default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= Settings.database.pool %>
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
  host: <%= Settings.database.host %>
  database: <%= Settings.database.database %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

